
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 15
VisualStudioVersion = 15.0.26730.12
MinimumVisualStudioVersion = 10.0.40219.1
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Dockerfile", "src\Dockerfile.csproj", "{A8D1F775-4BD3-41CA-91F9-161D0570D27C}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Dockerfile.Tests", "tests\Dockerfile.Tests.csproj", "{496AE203-5649-4198-9E9D-C34477689ED5}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{A8D1F775-4BD3-41CA-91F9-161D0570D27C}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{A8D1F775-4BD3-41CA-91F9-161D0570D27C}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{A8D1F775-4BD3-41CA-91F9-161D0570D27C}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{A8D1F775-4BD3-41CA-91F9-161D0570D27C}.Release|Any CPU.Build.0 = Release|Any CPU
		{496AE203-5649-4198-9E9D-C34477689ED5}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{496AE203-5649-4198-9E9D-C34477689ED5}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{496AE203-5649-4198-9E9D-C34477689ED5}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{496AE203-5649-4198-9E9D-C34477689ED5}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {051B31EE-126B-4117-AC64-9D2A052357BC}
	EndGlobalSection
EndGlobal
